export const WORD_POOL = [
  'apple', 'anchor', 'astronaut', 'amazon', 'avalanche', 'band', 'bank', 'bar', 'battery', 'beach',
  'bell', 'bird', 'block', 'board', 'bolt', 'bomb', 'bridge', 'brush', 'butter', 'cable',
  'camel', 'candy', 'capital', 'card', 'castle', 'cat', 'cell', 'center', 'charge', 'check',
  'chest', 'circle', 'club', 'code', 'comet', 'copper', 'cotton', 'court', 'crane', 'cross',
  'crown', 'cycle', 'dance', 'date', 'deck', 'diamond', 'doctor', 'dog', 'dragon', 'dream',
  'drill', 'eagle', 'engine', 'eye', 'face', 'fan', 'field', 'fighter', 'file', 'fire',
  'fish', 'flute', 'forest', 'fork', 'gas', 'ghost', 'giant', 'glass', 'glove', 'gold',
  'grace', 'grass', 'guitar', 'hammer', 'harbor', 'heart', 'helm', 'honey', 'hook', 'hotel',
  'ice', 'island', 'jacket', 'jet', 'joker', 'judge', 'kettle', 'key', 'knife', 'knight',
  'lab', 'laser', 'law', 'lead', 'lemon', 'light', 'line', 'lock', 'log', 'lottery',
  'mail', 'map', 'mask', 'match', 'mercury', 'mint', 'model', 'moon', 'mountain', 'mouse',
  'needle', 'ninja', 'note', 'nut', 'oasis', 'olive', 'opera', 'orange', 'orbit', 'organ',
  'palm', 'paper', 'park', 'party', 'pen', 'phoenix', 'piano', 'pilot', 'pin', 'pipe',
  'pirate', 'plane', 'plate', 'pocket', 'poison', 'pool', 'port', 'post', 'pound', 'press',
  'prince', 'pumpkin', 'queen', 'radio', 'ray', 'ring', 'river', 'rocket', 'root', 'rose',
  'salt', 'scale', 'school', 'server', 'shadow', 'ship', 'shoe', 'shop', 'shot', 'silver',
  'sketch', 'sky', 'smoke', 'snail', 'snow', 'sound', 'space', 'spider', 'spike', 'spirit',
  'spring', 'square', 'stage', 'star', 'station', 'steel', 'stone', 'storm', 'stream', 'strike',
  'sun', 'sword', 'table', 'tank', 'tap', 'temple', 'theater', 'thief', 'thread', 'tiger',
  'tower', 'track', 'train', 'triangle', 'tunnel', 'vacuum', 'valley', 'vault', 'vector', 'violin',
  'wall', 'watch', 'water', 'wave', 'web', 'wheel', 'wind', 'wire', 'wizard', 'wolf',
  'yard', 'zebra'
];
